// Estilos inline del reproductor de review. Separados de VideoPlayer.tsx por volumen: son datos,
// no lógica, y ocupaban un tercio del archivo.

import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "row",
    flex: 1,
    minHeight: 0,
    width: "100%",
    backgroundColor: "var(--bg-app)",
    overflow: "hidden",
  },
  leftColumn: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "var(--space-4)",
    gap: "var(--space-4)",
    minWidth: 0,
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    padding: "var(--space-4)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    zIndex: 10,
    background: "linear-gradient(to bottom, rgba(0,0,0,0.6), transparent)",
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
  },
  shareBtn: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    background: "var(--accent-violet)",
    color: "#fff",
    border: "none",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-2) var(--space-4)",
    fontWeight: 700,
    fontSize: "var(--font-xs)",
    cursor: "pointer",
  },
  videoWrapper: {
    flex: 1,
    position: "relative",
    backgroundColor: "#000",
    borderRadius: "var(--radius-lg)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  video: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
  centerOverlay: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  // En pantalla completa no hay baraja, asi que el transporte vuelve a flotar
  // sobre el video.
  transportOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: "var(--space-3) var(--space-4)",
    background: "linear-gradient(to top, rgba(0,0,0,0.85), transparent)",
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
  },
  // Acoplado a la baraja: sin degradado encima del video, y separado de la tira
  // por una linea, no por un hueco. Son una sola herramienta.
  transportDocked: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    padding: "0 0 var(--space-3) 0",
    borderBottom: "1px solid var(--line-soft)",
  },
  videoPlayBtn: {
    background: "transparent",
    border: "none",
    color: "#fff",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 var(--space-2)",
  },
  playbackSelect: {
    background: "transparent",
    color: "var(--text-secondary)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "4px",
    padding: "2px 4px",
    fontSize: "12px",
    outline: "none",
    cursor: "pointer",
    marginLeft: "8px",
  },
  videoTime: {
    color: "#fff",
    fontSize: "var(--font-xs)",
    fontWeight: 600,
    fontFamily: "var(--font-mono)",
  },
  volumeContainer: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
  },
  volumeSlider: {
    width: "80px",
    accentColor: "var(--accent-violet)",
    cursor: "pointer",
    height: "4px",
    borderRadius: "2px",
    appearance: "none",
    background: "var(--bg-card)",
  },
  // La "baraja": transporte + linea de tiempo + acciones, una sola superficie.
  // Antes era un panel de cristal esmerilado flotando aparte; el desenfoque y la
  // sombra grande son de los detalles que mas envejecen una interfaz, y ademas
  // reforzaban la idea de que la tira era otra cosa distinta del transporte.
  deck: {
    height: "178px",
    background: "var(--panel)",
    borderRadius: "var(--radius-lg)",
    border: "1px solid var(--line-soft)",
    padding: "var(--space-3) var(--space-4) var(--space-4)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-3)",
  },
  timelineHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  apmLabel: {
    color: "var(--text-secondary)",
    fontSize: "var(--font-xs)",
    fontWeight: 600,
  },
  snapLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    color: "var(--text-secondary)",
    fontSize: "var(--font-xs)",
    fontWeight: 600,
    fontFamily: "var(--font-mono)",
    marginRight: "auto",
    marginLeft: "var(--space-4)",
  },
  // Tira de saltos de cámara al pie del gráfico de APM.
  snapStrip: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "12px",
    pointerEvents: "none",
    zIndex: 3,
  },
  snapTick: {
    position: "absolute",
    bottom: 0,
    width: "2px",
    height: "100%",
    marginLeft: "-1px",
    background: "var(--accent-teal)",
    opacity: 0.75,
    borderRadius: "1px",
  },
  timelineHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
  },
  ghostBtn: {
    background: "transparent",
    border: "none",
    color: "var(--text-secondary)",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "var(--font-xs)",
    cursor: "pointer",
  },
  timelineGraph: {
    flex: 1,
    position: "relative",
    cursor: "pointer",
    marginTop: "var(--space-2)",
  },
  graphSvg: {
    width: "100%",
    height: "100%",
    position: "absolute",
    inset: 0,
  },
  eventNode: {
    position: "absolute",
    bottom: "24px", // Ajustado a la nueva altura
    width: "24px",  // Área de clic ligeramente mayor
    height: "24px",
    borderRadius: "50%",
    border: "2.5px solid", // Borde con más presencia
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "transform 0.2s cubic-bezier(0.34, 1.56, 0.64, 1), box-shadow 0.2s ease",
    cursor: "pointer",
    boxShadow: "0 2px 8px rgba(0,0,0,0.5)", // Sombra de contacto
  },
  playhead: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: "2px",
    backgroundColor: "#fff",
    pointerEvents: "none",
    zIndex: 20,
    opacity: 0.9,
    boxShadow: "0 0 8px rgba(255,255,255,0.8)",
  },
  playheadHover: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: "1px",
    backgroundColor: "var(--accent-violet)",
    pointerEvents: "none",
    zIndex: 15,
    opacity: 0.5,
  },
  axisMarks: {
    position: "absolute",
    bottom: "-15px",
    left: 0,
    right: 0,
  },
  rightColumn: {
    width: "380px",
    flexShrink: 0,
    position: "relative",
    backgroundColor: "var(--bg-sidebar)",
    borderLeft: "1px solid var(--border-subtle)",
    display: "flex",
    flexDirection: "column",
  },
  resizeHandle: {
    position: "absolute",
    left: "-3px",
    top: 0,
    bottom: 0,
    width: "7px",
    cursor: "ew-resize",
    zIndex: 30,
  },
  reviewHeader: {
    padding: "var(--space-4)",
    textAlign: "center",
  },
  reviewTitle: {
    color: "#fff",
    fontSize: "var(--font-sm)",
    fontWeight: 700,
  },
  // El resultado ya lo sabes al abrir la partida: no necesita un circulo de 48px
  // con degradado y glow presidiendo la barra lateral. Una linea con la franja
  // de estado dice lo mismo y devuelve el espacio a lo que si se consulta.
  reviewScoreCard: {
    flexShrink: 0,
    padding: "var(--space-3) var(--space-4)",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "var(--space-3)",
    textAlign: "left",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
  },
  scoreText: {
    margin: 0,
    fontFamily: "var(--font-mono)",
    fontSize: "13px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    fontWeight: 600,
  },
  scoreSub: {
    margin: "2px 0 0 0",
    fontFamily: "var(--font-mono)",
    color: "var(--faint)",
    fontSize: "11px",
    lineHeight: 1.4,
  },
  reviewList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "var(--space-4) 0",
  },
  timelineContainer: {
    position: "relative",
    padding: "0 var(--space-4)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-4)",
  },
  timelineLine: {
    position: "absolute",
    left: "21px", // 16px padding + 5px center of 10px dot
    top: "16px",
    bottom: "0",
    width: "2px",
    backgroundColor: "var(--border-subtle)",
    zIndex: 1,
  },
  reviewCardWrapper: {
    display: "flex",
    gap: "var(--space-3)",
    position: "relative",
    zIndex: 2,
    cursor: "pointer",
    transition: "opacity 0.2s, transform 0.2s",
  },
  timelineDot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    border: "2px solid",
    marginTop: "14px",
    flexShrink: 0,
    zIndex: 3,
  },
  reviewCard: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
    padding: "var(--space-3)",
    borderRadius: "var(--radius-md)",
    border: "1px solid",
    backdropFilter: "blur(8px)", // Glassmorphism
    WebkitBackdropFilter: "blur(8px)",
    transition: "background 0.2s, border-color 0.2s",
  },
  reviewCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  toneBadge: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "2px 6px",
    borderRadius: "4px",
  },
  reviewCardBody: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
  },
  reviewCardTitle: {
    color: "#fff",
    fontSize: "var(--font-sm)",
    fontWeight: 600,
  },
  reviewFooter: {
    flexShrink: 0,
    padding: "var(--space-4)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderTop: "1px solid var(--border-subtle)",
  },
  pageInfo: {
    color: "var(--text-muted)",
    fontSize: "11px",
    fontWeight: 600,
  },
  tabBar: {
    display: "flex",
    borderBottom: "1px solid var(--border-subtle)",
    padding: "0 var(--space-2)",
    flexShrink: 0,
  },
  tab: {
    flex: 1,
    background: "transparent",
    border: "none",
    borderBottom: "2px solid transparent",
    color: "var(--text-muted)",
    fontSize: "var(--font-sm)",
    fontWeight: 700,
    padding: "var(--space-3) var(--space-2)",
    cursor: "pointer",
    transition: "color 0.15s, border-color 0.15s",
  },
  tabActive: {
    color: "var(--accent-violet)",
    borderBottomColor: "var(--accent-violet)",
  },
  tabScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "var(--space-4)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-4)",
  },
  statGrid: {
    flexShrink: 0,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "var(--space-3)",
  },
  statTile: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-3)",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  statLabel: {
    color: "var(--text-muted)",
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: "0.4px",
    fontWeight: 700,
  },
  statValue: {
    color: "#fff",
    fontSize: "18px",
    fontWeight: 800,
    fontVariantNumeric: "tabular-nums",
  },
  notesArea: {
    width: "100%",
    minHeight: "220px",
    resize: "vertical",
    background: "var(--bg-card)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    color: "var(--text-primary)",
    fontSize: "var(--font-sm)",
    lineHeight: 1.6,
    padding: "var(--space-3)",
    outline: "none",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  notesHint: {
    color: "var(--text-muted)",
    fontSize: "11px",
    margin: 0,
  },
  nodeBadge: {
    position: "absolute",
    top: "-6px",
    right: "-6px",
    minWidth: "15px",
    height: "15px",
    padding: "0 3px",
    borderRadius: "8px",
    background: "var(--accent-violet)",
    color: "#fff",
    fontSize: "9px",
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 0 0 1.5px var(--bg-card)",
  },
  emptyEvents: {
    color: "var(--text-muted)",
    fontSize: "var(--font-sm)",
    textAlign: "center",
    padding: "var(--space-6) var(--space-4)",
  },
  // --- Scoreboard ---
  team: {
    flexShrink: 0,
    background: "var(--bg-card)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    overflow: "hidden",
  },
  teamHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "var(--space-2) var(--space-3)",
    fontWeight: 700,
    fontSize: "12px",
    borderBottom: "1px solid var(--border-subtle)",
  },
  playerRow: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    padding: "6px var(--space-3)",
    fontSize: "12px",
    borderBottom: "1px solid rgba(255,255,255,0.03)",
  },
  playerRowSelf: {
    background: "var(--accent-violet-soft)",
    boxShadow: "inset 3px 0 0 var(--accent-violet)",
  },
  champIcon: {
    width: "26px",
    height: "26px",
    borderRadius: "6px",
    background: "var(--bg-app)",
    flexShrink: 0,
    objectFit: "cover",
  },
  playerLevel: {
    color: "var(--text-muted)",
    width: "18px",
    textAlign: "center",
    fontVariantNumeric: "tabular-nums",
  },
  playerName: {
    flex: 1,
    fontWeight: 600,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  playerKda: {
    width: "64px",
    textAlign: "right",
    fontVariantNumeric: "tabular-nums",
  },
  playerCs: {
    width: "58px",
    textAlign: "right",
    color: "var(--text-muted)",
  },
  playerGold: {
    width: "46px",
    textAlign: "right",
    color: "var(--accent-gold)",
  },
  // --- Comentarios ---
  commentsWrap: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  commentsList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "var(--space-4)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
  },
  commentCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: "var(--space-2)",
    background: "var(--bg-card)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-2) var(--space-3)",
  },
  commentTime: {
    background: "var(--accent-violet-soft)",
    color: "var(--accent-violet)",
    border: "none",
    borderRadius: "4px",
    padding: "2px 6px",
    fontSize: "11px",
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
    cursor: "pointer",
    flexShrink: 0,
  },
  commentText: {
    flex: 1,
    fontSize: "13px",
    color: "var(--text-primary)",
    lineHeight: 1.5,
    wordBreak: "break-word",
  },
  commentDelete: {
    background: "transparent",
    border: "none",
    color: "var(--text-muted)",
    cursor: "pointer",
    padding: "2px",
    display: "flex",
    flexShrink: 0,
  },
  commentInputRow: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    padding: "var(--space-3)",
    borderTop: "1px solid var(--border-subtle)",
  },
  commentAtTime: {
    color: "var(--accent-violet)",
    fontSize: "11px",
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
    flexShrink: 0,
  },
  commentInput: {
    flex: 1,
    background: "var(--bg-card)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    color: "var(--text-primary)",
    fontSize: "13px",
    padding: "var(--space-2) var(--space-3)",
    outline: "none",
  },
  commentSend: {
    background: "var(--accent-violet)",
    border: "none",
    color: "#fff",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-2)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  // --- Scoreboard v2 (estilo Ascent) ---
  champWrap: { position: "relative", flexShrink: 0 },
  champLevel: {
    position: "absolute",
    bottom: "-3px",
    right: "-3px",
    background: "var(--bg-app)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "6px",
    fontSize: "9px",
    fontWeight: 800,
    padding: "0 3px",
    color: "var(--text-secondary)",
    lineHeight: "13px",
  },
  playerMid: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: "3px" },
  itemRow: { display: "flex", gap: "2px" },
  itemIcon: { width: "15px", height: "15px", borderRadius: "3px", background: "var(--bg-app)" },
  itemEmpty: { width: "15px", height: "15px", borderRadius: "3px", background: "rgba(255,255,255,0.04)" },
  playerKdaCol: { display: "flex", flexDirection: "column", alignItems: "flex-end", width: "62px", flexShrink: 0 },
  playerRatio: { color: "var(--text-muted)", fontSize: "10px" },
  playerNums: { display: "flex", flexDirection: "column", alignItems: "flex-end", width: "48px", flexShrink: 0 },
  syncBox: {
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "var(--space-2)",
    padding: "var(--space-5) var(--space-4)",
    background: "var(--bg-card)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    textAlign: "center",
  },
  syncText: { margin: 0, color: "var(--text-secondary)", fontSize: "13px" },
  syncBtn: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    background: "var(--accent-violet)",
    color: "#fff",
    border: "none",
    borderRadius: "var(--radius-md)",
    padding: "8px 14px",
    fontWeight: 700,
    fontSize: "13px",
    cursor: "pointer",
  },
  syncHint: { margin: 0, color: "var(--text-muted)", fontSize: "11px" },
  resyncBtn: {
    flexShrink: 0,
    alignSelf: "center",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    background: "transparent",
    color: "var(--text-muted)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    padding: "6px 12px",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  // --- Eventos v2 (estilo Ascent) ---
  featuredCard: {
    flexShrink: 0,
    margin: "24px 16px 8px", // Más margen exterior que interior (Principio Refactoring UI)
    background: "linear-gradient(145deg, rgba(40,42,50,0.8) 0%, rgba(20,22,28,0.9) 100%)", // Gradiente oscuro rico
    border: "1px solid rgba(255, 255, 255, 0.04)",
    borderRadius: "12px",
    padding: "20px", 
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    boxShadow: "0 8px 24px rgba(0,0,0,0.25)",
  },
  featuredTop: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  featuredTime: {
    background: "var(--accent-violet-soft)",
    color: "var(--accent-violet)",
    border: "none",
    borderRadius: "4px",
    padding: "2px 8px",
    fontSize: "11px",
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
    cursor: "pointer",
  },
  featuredName: { display: "flex", alignItems: "center", gap: "6px", color: "#fff", fontWeight: 700, fontSize: "14px" },
  featuredDesc: { margin: 0, color: "var(--text-secondary)", fontSize: "12px", lineHeight: 1.5 },
  filterChips: { flexShrink: 0, display: "flex", gap: "var(--space-2)", padding: "var(--space-3) var(--space-4) 0" },
  chip: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "16px",
    padding: "4px 12px",
    color: "var(--text-secondary)",
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  eventListV2: { 
    display: "flex", 
    flexDirection: "column",
    gap: "4px", // Separación entre filas en lugar de border-bottom
    padding: "0 8px"
  },
  eventRowV2: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 16px",
    cursor: "pointer",
    borderRadius: "8px",
    border: "1px solid transparent",
    transition: "background 0.2s ease, border-color 0.2s ease",
    fontSize: "13px",
  },
  eventRowV2Active: { 
    background: "rgba(255, 255, 255, 0.04)", 
    borderColor: "rgba(255, 255, 255, 0.08)",
    // Usamos boxShadow interno para el acento de color en lugar de borde izquierdo, 
    // lo que evita empujar el contenido
    boxShadow: "inset 4px 0 0 var(--accent-violet)" 
  },
  eventRowTime: { color: "var(--text-muted)", fontFamily: "var(--font-mono)", fontSize: "11px", width: "40px", flexShrink: 0 },
  eventRowLabel: { color: "#fff", fontWeight: 600 },
  // --- Your Performance ---
  perfBox: {
    flexShrink: 0,
    background: "var(--bg-card)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-3)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-3)",
  },
  perfHeader: { display: "flex", alignItems: "center", gap: "var(--space-3)" },
  perfChamp: { width: "40px", height: "40px", borderRadius: "8px", background: "var(--bg-app)" },
  perfTitle: { color: "#fff", fontWeight: 700, fontSize: "14px" },
  perfSub: { color: "var(--text-muted)", fontSize: "12px" },
  perfList: { display: "flex", flexDirection: "column" },
  perfRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "6px 0",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
    fontSize: "13px",
    color: "var(--text-muted)",
  },
  perfItems: { display: "flex", gap: "3px" },
  perfItem: { width: "26px", height: "26px", borderRadius: "5px", background: "var(--bg-app)" },
  perfItemEmpty: { width: "26px", height: "26px", borderRadius: "5px", background: "rgba(255,255,255,0.04)" },
  sectionTitle: {
    color: "var(--text-secondary)",
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.4px",
    marginBottom: "var(--space-2)",
  },
  objGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "var(--space-3)" },
  objCol: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-3)",
  },
  objTeam: { fontWeight: 700, fontSize: "12px", marginBottom: "var(--space-2)" },
  objRow: { display: "flex", justifyContent: "space-between", fontSize: "12px", color: "var(--text-muted)", padding: "3px 0" },
  buyGrid: { display: "flex", flexWrap: "wrap", gap: "var(--space-2)" },
  buyItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "2px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    padding: "4px",
    cursor: "pointer",
  },
  buyIcon: { width: "30px", height: "30px", borderRadius: "5px", background: "var(--bg-app)" },
  buyTime: { color: "var(--text-muted)", fontSize: "10px", fontFamily: "var(--font-mono)" },
};
