// Estilos inline del reproductor de review. Separados de VideoPlayer.tsx por volumen: son datos,
// no lógica, y ocupaban un tercio del archivo.

import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "row",
    flex: 1,
    minHeight: 0,
    width: "100%",
    background: "transparent",
    overflow: "hidden",
  },
  leftColumn: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "var(--space-4)",
    gap: "var(--space-4)",
    minWidth: 0,
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    padding: "var(--space-4)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    zIndex: 10,
    background: "linear-gradient(to bottom, rgba(0,0,0,0.6), transparent)",
  },
  topBarLeft: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
  },
  videoWrapper: {
    flex: 1,
    position: "relative",
    backgroundColor: "#000",
    borderRadius: "var(--radius-lg)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  video: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
  },
  centerOverlay: {
    position: "absolute",
    inset: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  // En pantalla completa no hay baraja: tira y transporte flotan juntos sobre
  // el video, dentro de fsBottom (que pone el degradado y la posición).
  transportOverlay: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
  },
  fsBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
    padding: "18px 16px 12px",
    background: "linear-gradient(to top, rgba(0,0,0,0.92), rgba(0,0,0,0.55) 70%, transparent)",
  },
  // La tira necesita alto propio: en la baraja lo heredaba del deck.
  fsTimeline: {
    height: 64,
    position: "relative",
    display: "flex",
    flexDirection: "column",
  },
  // Acoplado a la baraja: sin degradado encima del video, y separado de la tira
  // por una linea, no por un hueco. Son una sola herramienta.
  transportDocked: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    padding: "0 0 var(--space-3) 0",
    borderBottom: "1px solid var(--line-soft)",
  },
  volumeSlider: {
    width: "80px",
    accentColor: "var(--accent-violet)",
    cursor: "pointer",
    height: "4px",
    borderRadius: "2px",
    appearance: "none",
    background: "var(--sunken)",
    boxShadow: "var(--inset-sunken)",
  },
  // La "baraja": transporte + linea de tiempo + acciones, una sola superficie.
  // Antes era un panel de cristal esmerilado flotando aparte; el desenfoque y la
  // sombra grande son de los detalles que mas envejecen una interfaz, y ademas
  // reforzaban la idea de que la tira era otra cosa distinta del transporte.
  deck: {
    height: "178px",
    background: "var(--surface-1)",
    borderRadius: "var(--radius-lg)",
    border: "1px solid var(--line-soft)",
    padding: "var(--space-3) var(--space-4) var(--space-4)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-3)",
  },
  timelineHeaderRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  apmLabel: {
    color: "var(--text-secondary)",
    fontSize: "var(--font-xs)",
    fontWeight: 600,
  },
  snapLabel: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    color: "var(--text-secondary)",
    fontSize: "var(--font-xs)",
    fontWeight: 600,
    fontFamily: "var(--font-mono)",
    marginRight: "auto",
    marginLeft: "var(--space-4)",
  },
  // Tira de saltos de cámara al pie del gráfico de APM.
  snapStrip: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "12px",
    pointerEvents: "none",
    zIndex: 3,
  },
  // Una fila por carril dentro de la tira. 3 px de alto y 1 de aire: las tres
  // caben en los 12 px de la tira sin tocarse.
  snapLane: {
    position: "absolute",
    left: 0,
    right: 0,
    height: "3px",
  },
  snapTick: {
    position: "absolute",
    bottom: 0,
    width: "2px",
    height: "100%",
    marginLeft: "-1px",
    background: "var(--accent-teal)",
    opacity: 0.75,
    borderRadius: "1px",
  },
  timelineHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-3)",
  },
  ghostBtn: {
    background: "transparent",
    border: "none",
    color: "var(--text-secondary)",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    fontSize: "var(--font-xs)",
    cursor: "pointer",
  },
  timelineGraph: {
    flex: 1,
    position: "relative",
    cursor: "pointer",
    marginTop: "var(--space-2)",
  },
  graphSvg: {
    width: "100%",
    height: "100%",
    position: "absolute",
    inset: 0,
  },
  eventNode: {
    position: "absolute",
    bottom: "24px", // Ajustado a la nueva altura
    width: "24px",  // Área de clic ligeramente mayor
    height: "24px",
    borderRadius: "50%",
    border: "2.5px solid", // Borde con más presencia
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "transform 0.2s cubic-bezier(0.34, 1.56, 0.64, 1), box-shadow 0.2s ease",
    cursor: "pointer",
    boxShadow: "0 2px 8px rgba(0,0,0,0.5)", // Sombra de contacto
  },
  playhead: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: "2px",
    backgroundColor: "#fff",
    pointerEvents: "none",
    zIndex: 20,
    opacity: 0.9,
    boxShadow: "0 0 8px rgba(255,255,255,0.8)",
  },
  playheadHover: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: "1px",
    backgroundColor: "var(--accent-violet)",
    pointerEvents: "none",
    zIndex: 15,
    opacity: 0.5,
  },
  axisMarks: {
    position: "absolute",
    bottom: "-15px",
    left: 0,
    right: 0,
  },
  rightColumn: {
    width: "380px",
    flexShrink: 0,
    position: "relative",
    backgroundColor: "var(--bg-sidebar)",
    borderLeft: "1px solid var(--border-subtle)",
    display: "flex",
    flexDirection: "column",
  },
  resizeHandle: {
    position: "absolute",
    left: "-3px",
    top: 0,
    bottom: 0,
    width: "7px",
    cursor: "ew-resize",
    zIndex: 30,
  },
  reviewHeader: {
    padding: "var(--space-4)",
    textAlign: "center",
  },
  reviewTitle: {
    color: "#fff",
    fontSize: "var(--font-sm)",
    fontWeight: 700,
  },
  reviewList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "var(--space-4) 0",
  },
  reviewCard: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
    padding: "var(--space-3)",
    borderRadius: "var(--radius-md)",
    border: "1px solid",
    backdropFilter: "blur(8px)", // Glassmorphism
    WebkitBackdropFilter: "blur(8px)",
    transition: "background 0.2s, border-color 0.2s",
  },
  reviewCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  toneBadge: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "2px 6px",
    borderRadius: "4px",
  },
  reviewCardBody: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
  },
  reviewCardTitle: {
    color: "#fff",
    fontSize: "var(--font-sm)",
    fontWeight: 600,
  },
  reviewFooter: {
    flexShrink: 0,
    padding: "var(--space-4)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderTop: "1px solid var(--border-subtle)",
  },
  pageInfo: {
    color: "var(--text-muted)",
    fontSize: "11px",
    fontWeight: 600,
  },
  tabBar: {
    display: "flex",
    borderBottom: "1px solid var(--border-subtle)",
    padding: "0 var(--space-2)",
    flexShrink: 0,
  },
  tab: {
    flex: 1,
    background: "transparent",
    border: "none",
    borderBottom: "2px solid transparent",
    color: "var(--text-muted)",
    fontSize: "var(--font-sm)",
    fontWeight: 700,
    padding: "var(--space-3) var(--space-2)",
    cursor: "pointer",
    transition: "color 0.15s, border-color 0.15s",
  },
  // Atajo caro: `tab` pone `borderBottom` (atajo) y esto ponia
  // `borderBottomColor` (propiedad larga). React avisa en cada render de que
  // mezclar los dos sobre el mismo valor produce bugs de estilo, y llenaba la
  // consola. Se dice entero.
  tabActive: {
    color: "var(--cool)",
    borderBottom: "2px solid var(--cool)",
  },
  emptyEvents: {
    color: "var(--text-muted)",
    fontSize: "var(--font-sm)",
    textAlign: "center",
    padding: "var(--space-6) var(--space-4)",
  },
  champIcon: {
    width: "26px",
    height: "26px",
    borderRadius: "6px",
    background: "var(--bg-app)",
    flexShrink: 0,
    objectFit: "cover",
  },
  // --- Comentarios ---
  commentsWrap: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  },
  commentsList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "var(--space-4)",
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-2)",
  },
  commentCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: "var(--space-2)",
    background: "var(--surface-1)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-2) var(--space-3)",
  },
  commentTime: {
    background: "var(--accent-violet-soft)",
    color: "var(--accent-violet)",
    border: "none",
    borderRadius: "4px",
    padding: "2px 6px",
    fontSize: "11px",
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
    cursor: "pointer",
    flexShrink: 0,
  },
  commentText: {
    flex: 1,
    fontSize: "13px",
    color: "var(--text-primary)",
    lineHeight: 1.5,
    wordBreak: "break-word",
  },
  commentDelete: {
    background: "transparent",
    border: "none",
    color: "var(--text-muted)",
    cursor: "pointer",
    padding: "2px",
    display: "flex",
    flexShrink: 0,
  },
  commentInputRow: {
    display: "flex",
    alignItems: "center",
    gap: "var(--space-2)",
    padding: "var(--space-3)",
    borderTop: "1px solid var(--border-subtle)",
  },
  commentAtTime: {
    color: "var(--accent-violet)",
    fontSize: "11px",
    fontWeight: 700,
    fontFamily: "var(--font-mono)",
    flexShrink: 0,
  },
  commentInput: {
    flex: 1,
    background: "var(--sunken)",
    boxShadow: "var(--inset-sunken)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "var(--radius-md)",
    color: "var(--text-primary)",
    fontSize: "13px",
    padding: "var(--space-2) var(--space-3)",
    outline: "none",
  },
  commentSend: {
    background: "var(--action)",
    border: "none",
    color: "var(--on-action)",
    borderRadius: "var(--radius-md)",
    padding: "var(--space-2)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  filterChips: { flexShrink: 0, display: "flex", gap: "var(--space-2)", padding: "var(--space-3) var(--space-4) 0" },
  chip: {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    background: "var(--surface-1)",
    border: "1px solid var(--border-subtle)",
    borderRadius: "16px",
    padding: "4px 12px",
    color: "var(--text-secondary)",
    fontSize: "12px",
    fontWeight: 700,
    cursor: "pointer",
  },
  eventListV2: { 
    display: "flex", 
    flexDirection: "column",
    gap: "4px", // Separación entre filas en lugar de border-bottom
    padding: "0 8px"
  },
  perfItem: { width: "26px", height: "26px", borderRadius: "5px", background: "var(--bg-app)" },
  perfItemEmpty: { width: "26px", height: "26px", borderRadius: "5px", background: "rgba(255,255,255,0.04)" },
  buyIcon: { width: "30px", height: "30px", borderRadius: "5px", background: "var(--bg-app)" },
};
